"""Agent Scaffolder - Write generated agent code to files."""

from pathlib import Path
from typing import Dict


class AgentScaffolder:
    """Scaffold agent code from templates.

    Outputs:
    - Agent Python file
    - __init__.py for imports
    - README.md for agent documentation
    """

    def __init__(self, output_dir: Path):
        """Initialize scaffolder.

        Args:
            output_dir: Directory to write agent files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def scaffold(self, template: Dict) -> Path:
        """Scaffold agent from template.

        Args:
            template: Agent template dictionary

        Returns:
            Path to generated agent file
        """
        agent_id = template["agent_id"]

        # Create agent directory
        agent_dir = self.output_dir / agent_id
        agent_dir.mkdir(parents=True, exist_ok=True)

        # Write agent code
        agent_file = agent_dir / f"{agent_id}.py"
        with open(agent_file, 'w') as f:
            f.write(template["code_template"])

        # Write __init__.py
        init_file = agent_dir / "__init__.py"
        with open(init_file, 'w') as f:
            f.write(self._generate_init(template))

        # Write README
        readme_file = agent_dir / "README.md"
        with open(readme_file, 'w') as f:
            f.write(self._generate_readme(template))

        return agent_file

    def _generate_init(self, template: Dict) -> str:
        """Generate __init__.py content.

        Args:
            template: Agent template

        Returns:
            __init__.py content
        """
        class_name = self._to_camel_case(template["name"]) + "Agent"

        return f'''"""{ template["name"]} - Auto-generated agent.

{template["description"]}
"""

from .{template["agent_id"]} import {class_name}, create_agent

__all__ = ["{class_name}", "create_agent"]
'''

    def _generate_readme(self, template: Dict) -> str:
        """Generate README.md content.

        Args:
            template: Agent template

        Returns:
            README content
        """
        inputs_table = self._format_inputs_table(template.get("inputs", []))
        outputs_table = self._format_outputs_table(template.get("outputs", []))

        return f'''# {template["name"]}

{template["description"]}

## Agent Metadata

- **Agent ID:** `{template["agent_id"]}`
- **Tier:** {template["tier"]}
- **Model:** {template["model"]}
- **Capabilities:** {", ".join(template["capabilities"])}

## Inputs

{inputs_table}

## Outputs

{outputs_table}

## Usage

```python
from {template["agent_id"]} import create_agent

# Create agent instance
agent = create_agent()

# Execute agent
result = await agent.execute(
    # Pass your inputs here
)

print(result)
```

## Dependencies

{self._format_dependencies(template.get("dependencies", []))}

---

*Auto-generated by LearnQwest Agent Conversion Pipeline*
*Generation Date: {self._get_timestamp()}*
'''

    def _format_inputs_table(self, inputs: list) -> str:
        """Format inputs as markdown table."""
        if not inputs:
            return "No inputs defined."

        lines = ["| Name | Type | Description |", "|------|------|-------------|"]

        for inp in inputs:
            lines.append(f"| {inp['name']} | {inp.get('type', 'any')} | {inp.get('description', '-')} |")

        return "\n".join(lines)

    def _format_outputs_table(self, outputs: list) -> str:
        """Format outputs as markdown table."""
        if not outputs:
            return "No outputs defined."

        lines = ["| Name | Type | Description |", "|------|------|-------------|"]

        for out in outputs:
            lines.append(f"| {out['name']} | {out.get('type', 'any')} | {out.get('description', '-')} |")

        return "\n".join(lines)

    def _format_dependencies(self, dependencies: list) -> str:
        """Format dependencies as bullet list."""
        if not dependencies:
            return "No external dependencies."

        return "\n".join(f"- `{dep}`" for dep in dependencies)

    def _to_camel_case(self, text: str) -> str:
        """Convert to CamelCase."""
        words = text.replace("_", " ").replace("-", " ").split()
        return "".join(word.capitalize() for word in words)

    def _get_timestamp(self) -> str:
        """Get current timestamp."""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
